################################################################################
# aws-kms-pkcs11
################################################################################
AWS_KMS_PKCS11_VERSION_MAJOR = 0
AWS_KMS_PKCS11_VERSION_MINOR = 0
AWS_KMS_PKCS11_VERSION_PATCH = 17
AWS_KMS_PKCS11_VERSION = v$(AWS_KMS_PKCS11_VERSION_MAJOR).$(AWS_KMS_PKCS11_VERSION_MINOR).$(AWS_KMS_PKCS11_VERSION_PATCH)
AWS_KMS_PKCS11_SITE_METHOD = git
AWS_KMS_PKCS11_SITE = https://github.com/JackOfMostTrades/aws-kms-pkcs11.git
HOST_AWS_KMS_PKCS11_DEPENDENCIES += \
	host-aws-sdk-cpp \
	host-openssl \
	host-p11-kit \
	host-json-c \
	host-libp11 \
	host-pkgconf \
	host-pkcs11-provider \
	host-python3 \
	host-python-asn1crypto
AWS_KMS_PKCS11_LICENSE = MIT
AWS_KMS_PKCS11_LICENSE_FILES = LICENSE
HOST_AWS_KMS_PKCS11_ENV += \
	AWS_SDK_PATH=$(HOST_DIR) \
	AWS_SDK_LIB_PATH=$(HOST_DIR)/lib \
	PKCS11_INC=-I$(HOST_DIR)/include/p11-kit-1/p11-kit \
	PKCS11_MOD_PATH=$(HOST_DIR)/lib/pkcs11 \
	JSON_C_INC=-I$(HOST_DIR)/include/json-c \
	LIBRARY_PATH="$(HOST_DIR)/lib:$(LIBRARY_PATH)"

define HOST_AWS_KMS_PKCS11_BUILD_CMDS
	$(HOST_MAKE_ENV) $(HOST_AWS_KMS_PKCS11_ENV) $(MAKE) -C $(@D) $(HOST_CONFIGURE_OPTS)
	# Create versioned .so and symlinks (idempotent for rebuilds)
	if [ -f $(@D)/aws_kms_pkcs11.so -a ! -L $(@D)/aws_kms_pkcs11.so ]; then \
		mv $(@D)/aws_kms_pkcs11.so \
			$(@D)/aws_kms_pkcs11.so.$(AWS_KMS_PKCS11_VERSION_MAJOR).$(AWS_KMS_PKCS11_VERSION_MINOR).$(AWS_KMS_PKCS11_VERSION_PATCH); \
	fi
	ln -sf aws_kms_pkcs11.so.$(AWS_KMS_PKCS11_VERSION_MAJOR).$(AWS_KMS_PKCS11_VERSION_MINOR).$(AWS_KMS_PKCS11_VERSION_PATCH) $(@D)/aws_kms_pkcs11.so.$(AWS_KMS_PKCS11_VERSION_MAJOR)
	ln -sf aws_kms_pkcs11.so.$(AWS_KMS_PKCS11_VERSION_MAJOR) $(@D)/aws_kms_pkcs11.so
endef

define HOST_AWS_KMS_PKCS11_INSTALL_CMDS
	cp -P $(@D)/aws_kms_pkcs11.so* $(HOST_DIR)/lib/pkcs11/

	# Note: the ARN-dependent multi-slot config (aws-kms-pkcs11-config.json) is
	# NOT generated here.  It is (re)generated by the host-summit-key-provider
	# build step (via HSM_GEN_CONFIG_CMD in backends/aws-kms/aws-kms.mk) so that
	# a single `host-summit-key-provider-rebuild` picks up ARN changes; this
	# install step is stamp-cached and would otherwise leave the config stale.
	# The module-path wiring below is ARN-independent and stays here.
	$(SED) '/^pkcs11-module-path/d' $(HOST_DIR)/host_pkcs11config.cnf
	$(SED) '/\[pkcs11_sect\]/a pkcs11-module-path = \
		$(HOST_DIR)\/lib\/pkcs11\/aws_kms_pkcs11.so.$(AWS_KMS_PKCS11_VERSION_MAJOR)' $(HOST_DIR)/host_pkcs11config.cnf
endef

$(eval $(host-generic-package))
