################################################################################
#
# summit-usbgadget
#
################################################################################

SUMMIT_USBGADGET_VERSION = local
SUMMIT_USBGADGET_SITE = $(BR2_EXTERNAL_SUMMIT_SOM_PATH)/externals/summit-usbgadget
SUMMIT_USBGADGET_SITE_METHOD = local

SUMMIT_USBGADGET_LICENSE = Ezurio
SUMMIT_USBGADGET_LICENSE_FILES = LICENSE.ezurio

SUMMIT_USBGADGET_DEPENDENCIES += \
	$(if $(BR2_PACKAGE_SUMMIT_USBGADGET_USB),udev,) \
	$(if $(filter y,$(BR2_PACKAGE_SUMMIT_USBGADGET_DFU) $(BR2_PACKAGE_SUMMIT_USBGADGET_FASTBOOT_USB) $(BR2_PACKAGE_SUMMIT_USBGADGET_FASTBOOT_TCP) $(BR2_PACKAGE_SUMMIT_USBGADGET_SOCKET)),swupdate,) \
	$(if $(BR2_PACKAGE_SUMMIT_USBGADGET_SOCKET_TLS),openssl,)

SUMMIT_USBGADGET_FEATURES = \
	$(if $(BR2_PACKAGE_SUMMIT_USBGADGET_USB),usb,) \
	$(if $(BR2_PACKAGE_SUMMIT_USBGADGET_DFU),dfu,) \
	$(if $(BR2_PACKAGE_SUMMIT_USBGADGET_FASTBOOT_USB),fastboot-usb,) \
	$(if $(BR2_PACKAGE_SUMMIT_USBGADGET_FASTBOOT_TCP),fastboot-tcp,) \
	$(if $(BR2_PACKAGE_SUMMIT_USBGADGET_SOCKET),socket,) \
	$(if $(BR2_PACKAGE_SUMMIT_USBGADGET_SOCKET_TLS),socket-tls,)

SUMMIT_USBGADGET_CARGO_BUILD_OPTS += \
	--no-default-features \
	$(if $(strip $(SUMMIT_USBGADGET_FEATURES)),--features $(subst $() $(),$(comma),$(strip $(SUMMIT_USBGADGET_FEATURES))),)

SUMMIT_USBGADGET_CARGO_INSTALL_OPTS = $(SUMMIT_USBGADGET_CARGO_BUILD_OPTS) --profile release

SUMMIT_USBGADGET_CARGO_ENV += \
	RUSTFLAGS="--remap-path-prefix=$(SUMMIT_USBGADGET_SRCDIR)=." \
	SWUPDATE_INCLUDE_DIR="$(STAGING_DIR)/usr/include" \
	CARGO_PROFILE_RELEASE_LTO="true"

ifeq ($(BR2_PACKAGE_SUMMIT_FIREWALL),)
ifneq ($(BR2_PACKAGE_SUMMIT_NETWORK_MANAGER)$(BR2_PACKAGE_NETWORK_MANAGER),)
define SUMMIT_USBGADGET_INSTALL_NM
	$(INSTALL) -D -m 0600 -t $(TARGET_DIR)/usr/lib/NetworkManager/system-connections/ \
		$(SUMMIT_USBGADGET_PKGDIR)/shared-usb*.nmconnection
endef
SUMMIT_USBGADGET_POST_INSTALL_TARGET_HOOKS += SUMMIT_USBGADGET_INSTALL_NM
endif
endif

define SUMMIT_USBGADGET_INSTALL_CONFIG
	$(INSTALL) -D -m 0644 $(SUMMIT_USBGADGET_PKGDIR)/summit-usbgadget.toml \
		$(TARGET_DIR)/etc/summit-usbgadget.toml
endef
SUMMIT_USBGADGET_POST_INSTALL_TARGET_HOOKS += SUMMIT_USBGADGET_INSTALL_CONFIG

define SUMMIT_USBGADGET_INSTALL_INIT_SYSTEMD
	$(INSTALL) -D -m 0644 $(SUMMIT_USBGADGET_PKGDIR)/summit-usbgadget.service \
		$(TARGET_DIR)/usr/lib/systemd/system/summit-usbgadget.service
endef

define SUMMIT_USBGADGET_INSTALL_INIT_SYSV
	$(INSTALL) -D -m 0755 $(SUMMIT_USBGADGET_PKGDIR)/summit-usbgadget.init \
		$(TARGET_DIR)/etc/init.d/S43summit-usbgadget
endef

$(eval $(cargo-package))
